name: Deploy BMS Production Client

on: workflow_dispatch

jobs:
  deploy_production:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: './bms/package-lock.json'

      - name: Create Env File
        run: |
          touch .env
          echo "${{ secrets.ENV_PROD }}" >> .env

      - name: Install Dependencies
        run: npm install
        working-directory: ./bms

      - name: Build
        run: CI= npm run build
        working-directory: ./bms

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Upload to S3
      #   run: |
      #     aws s3 mv --region ap-northeast-2 \
      #     build \
      #     ${{ secrets.S3_PROD_FRONT_LOCATION }}
      #   working-directory: ./bms

      - name: Sync to S3
        run: |
          aws s3 sync build ${{ secrets.S3_PROD_FRONT_LOCATION }} \
            --region ap-northeast-2 --delete
        working-directory: ./bms

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_PROD_DISTRIBUTION_ID }} \
            --paths "/*"
